name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Lints code
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Uberjar
        run: lein lint

  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '11', '13', '15' ]
        clojure: [ '1.5', '1.6', '1.7', '1.8', '1.9', '1.10' ]
    name: Build with Clojure ${{ matrix.clojure }} on Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }} 
      - name: Install dependencies
        run: lein with-profile +${{ matrix.clojure }} deps
      - name: Combile
        run: lein with-profile +${{ matrix.clojure }} compile
      - name: Uberjar
        run: lein with-profile +${{ matrix.clojure }} uberjar
