name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '7', '8', '11', '13', '15' ]
        clojure: [ '1.5', '1.6', '1.7', '1.8', '1.9' ]
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }} 
      - name: Install dependencies
        run: lein with-profile ${{ matrix.clojure }} deps
      - name: Combile
        run: lein with-profile ${{ matrix.clojure }} compile
      - name: Uberjar
        run: lein with-profile ${{ matrix.clojure }} uberjar
